### ISSUE TITLE
execa (dependency) should probably be updated

### ISSUE THREAD

**Issue by binduwavell** [ghooks-org/ghooks#103]
ghooks@1.2.1 > execa@0.2.2 > cross-spawn-async@2.2.4

cross-spawn-async requires a build toolchain. So moving to execa @ 0.4.0 which uses cross-spawn @ 3.0.0 you remove the need at least in this instance for a compiler. This should allow the package to install faster and also make it compatible with more environments.

**Comment by ta2edchimp** [comment]
We already have execa@0.4.0 included as a dependency ( see #94 ), but no release has been triggered yet.
I hope to see my PR ( #81 ) merged anytime soon, that would initiate a new release.

**Comment by binduwavell** [comment]
Turns out cross-spawn @ 3.0.0 may not be sufficient to support node 7, may require @ 4.0.0 which does not appear to be supported by execa yet.

**Comment by jhabdas** [comment]
@ta2edchimp do you know if this can be closed?

**Comment by ta2edchimp** [comment]
Uh... I'm on the move today and the next two days, but if should tell from the back of my head, ghooks 2.0.0 depends on execa 0.5.0, which includes cross-spawn ^4.0.0... and I am pretty sure not having seen any traces of compilation during the last "npm installs" that included ghooks@2.0.0.  
I would leave this issue open until we can be absolutely sure.

**Comment by jhabdas** [comment]
Closing issue until we're sure it's an issue. Please reopen if needed.
