### ISSUE TITLE
Cleanup modified hooks after npm uninstall

### ISSUE THREAD

**Issue by vitalets** [ghooks-org/ghooks#164]
I'm using ghooks for several projects but for one project I decided to uninstall it.
After `npm un ghooks` I'm getting error on every commit:

```
ghooks not found!
Make sure you have it installed on your "node_modules".
Skipping git hooks.
```

Is it possible to cleanup modified hooks automatically?
thx!

**Comment by kentcdodds** [comment]
I just delete my `.git/hooks` directory. I wonder if there's an `uninstall` script that we could use...

**Comment by vitalets** [comment]
Yes, sure i can do it.
But maybe it's better to keep `hooks/*.sample` for the future.
I end up with the following command that removes all hooks not ending with `.sample`:
```bash
cd .git/hooks
ls | grep \.sample -v | xargs rm
```

**Comment by kentcdodds** [comment]
I think it'd be even better to add a `postuninstall` script in our `npm scripts` just like we have [an `install` script](https://github.com/gtramontina/ghooks/blob/6e601bed7db8d61c1174856cf3dac5769958a679/package.json#L32).

Would you like to [makeapullrequest.com](http://makeapullrequest.com)? Make sure that it works on windows too!

**Comment by okonet** [comment]
Also run into this one.

**Comment by kentcdodds** [comment]
I definitely just recommend switching to husky: https://github.com/gtramontina/ghooks/issues/166

**Comment by jhabdas** [comment]
@kentcdodds after 7 months of husky perhaps you could share your experiences as to how it works under the scenario described in the OP?

**Comment by kentcdodds** [comment]
Honestly, this is never really something I notice. But I'm pretty sure that husky uninstalls properly IIRC.

**Comment by jhabdas** [comment]
Thanks Kent, will keep that in consideration. For now the messaging in place should suffice. Pulls welcome.
