### ISSUE TITLE
ghooks is tied to project folder, thus relocate project folder breaks ghooks

### ISSUE THREAD

**Issue by ApolloTang** [ghooks-org/ghooks#198]
After digging around I found that, for example, in  '../path/to/project/.git/hooks/commit-msg',
the script template had set node_modules paths as:
 
```
var nodeModulesPath = '/Users/apollotang/Desktop/webpeck-deep-dive/v01/es6-todomvc/node_modules';
```

Meaning, if I relocate project folder from ~/Desktop to ~/Projects, I will no longer able to do git checkout unless I manually edit nodeModulesPath in every hook in .git/hooks to:

```
var nodeModulesPath = path.resolve('../../node_modules');
```

Or alternately, start all over to regenerate new node_modules path.

**Comment by jhabdas** [comment]
@ApolloTang do you know how Husky handles this kind of behavior? what would your ideal scenario be for moving projects around?

**Comment by ta2edchimp** [comment]
As a note for further investigation, [this line in the template](https://github.com/ghooks-org/ghooks/blob/master/lib/hook.template.js#L9) should make use of [`path.relative(from, to)`](https://nodejs.org/api/path.html#path_path_relative_from_to)

**Comment by jhabdas** [comment]
@ta2edchimp thanks. if we're backed by unit tests I'll look at a pull for that. otherwise we need unit tests and code coverage

**Comment by jhabdas** [comment]
Closing without response from issue creator in over 3 weeks.
