### ISSUE TITLE
Issues using with NPM link

### ISSUE THREAD

**Issue by PeteStein** [ghooks-org/ghooks#206]
This module, even as a dependency of another module, infiltrates the parent .git folder and installs git hooks that are broken and/or platform dependent. The fact that you have another issue related to incompatibility with GUI git clients, and that you suggest changing how those clients are launched, is absolutely ridiculous.

This module is worse than broken -- it's a hazard to other projects that causes mysterious failures. A node module should not be manipulating such critical files in such a sloppy way. Frankly, this whole project should be disabled and/or banned from the NPM registry immediately.

**Comment by gtramontina** [comment]
I'm sorry you feel this way. 😞 This project has helped countless teams throughout its lifetime (and [still is](https://libraries.io/npm/ghooks/dependent-repositories) even though it has already been deprecated for [reasons other than "being broken"](https://github.com/gtramontina/ghooks/issues/166)).

I'd be more than happy to help you out with any problems you might be experiencing with `ghooks`.

**Comment by PeteStein** [comment]
The issue is that I installed another module that references ghooks; is it intended that ghooks would modify my hooks without any prompting? As soon as it was installed, all git commands fail on my machine with the #40 issue. I just feel like if there are issues with platform-specific scripts, then there should not be any sort of automatic modifications of anything without user approval.

**Comment by ta2edchimp** [comment]
Could you point us to the module that you have installed, which references ghooks?
To me, this sounds like an erroneous use of ghooks as a normal dependency, rather than as a devDependency.

**Comment by PeteStein** [comment]
It's "videogular2" which is being pulled in locally with npm-link (since it needed some customization to get past a TS issue), so perhaps that is related to what I'm seeing?

**Comment by ta2edchimp** [comment]
Ok, that particular module does have ghooks correctly set as devDependency...

I also have some packages pulled in locally using npm link myself. Almost all of them depend upon ghooks and never have I experienced such a behavior. If you have the patience, I'll have a look into the issue but it might take a couple of days until I'll find the time to do so.

**Comment by ta2edchimp** [comment]
Btw. thank you very much for "softening" the title 😉

**Comment by PeteStein** [comment]
No worries, there were definitely some incorrect assumptions made as far as what the typical behavior is supposed to be. I want to be able to say that I did something unconventional to trigger it, but all I can point to is that my project was set up in a workspace in my CI, and I realized that  clearing the workspace would let me pull from Git again, but upon performing a pull after the initial one, the hooks were already installed and the pull would fail. Maybe an errant npm install from within the videogular2 folder would cause the hooks to be installed two levels up? I'm fairly certain I never installed ghooks directly into the top-level project folder.

In any case, I definitely appreciate your attention and the immediate response, although given that I'm already linking the module, I've gotten past the issue by just removing the ghooks reference for now. If you can't reproduce then feel free to close the issue if there's nothing else to look into.

**Comment by jhabdas** [comment]
Lots of words. Bit of unhealthy rage. Anything actionable here @PeteStein or can this be closed?
