### ISSUE TITLE
Remove deprecation notice

### ISSUE THREAD

**Issue by jhabdas** [ghooks-org/ghooks#212]
https://github.com/ghooks-org/ghooks/issues/209 related.

Need to figure out what's needed to remove the deprecation notice. I've updated the repo title to `[CURRENTLY DEPRECATED]` to hint at revival. Will dig into this at some point unless some in the org (current or future) gets to it first.

**Comment by gtramontina** [comment]
To "undeprecate" it with npm, it is just a matter of setting the deprecation message to an empty string, as per the docs https://docs.npmjs.com/cli/deprecate

> To un-deprecate a package, specify an empty string ("") for the message argument.

**Comment by jhabdas** [comment]
@gtramontina thanks. I will look into taking care of this with a new minor as soon as I'm able to get off my current network, which is blocking my 22 and preventing PGP.

**Comment by gtramontina** [comment]
Done! 👍 A `patch` release went out with https://github.com/ghooks-org/ghooks/pull/218.

**Comment by G-Rath** [comment]
@gtramontina given that the poster has deleted their github account, and ghooks hasn't seen a new version or activity (aside from dependabot) in a few years, might be time to re-deprecate the package to reduce confusion?

(I stumbled upon an old project using this and had to hunt around a bit to confirm that it's been abandonded).
