### ISSUE TITLE
Re-enable Greenkeeper?

### ISSUE THREAD

**Issue by gtramontina** [ghooks-org/ghooks#213]
I used to have greenkeeper enabled on ghooks (although not being able to keep up with the PRs). What about re-enabling it?

More info: https://greenkeeper.io/

**Comment by ta2edchimp** [comment]
I have not used greenkeeper since they changed how they communicate dependencies being update. I came to the habit of pinning the dependencies of the projects I maintain to fixed versions and running [`ncu`](https://www.npmjs.com/package/npm-check-updates) over them once in a while.

**Comment by jhabdas** [comment]
Closing as nice to have. `npm outdated` does the trick.
