### ISSUE TITLE
Drop transpilation

### ISSUE THREAD

**Issue by ta2edchimp** [ghooks-org/ghooks#217]
IMO we should drop the transpilation step when releasing a revived version. I just had a (very) quick look into the sources and do not see anything that really requires us to transpile, when we would drop support for older Node versions at least.

This would have the benefit of being able to also npm install ghooks from its repo or from a fork (like described here: #216 ), using it right away instead of having to cope with the transpilation step (`dist` folder being _only_ created upon build, prior to publishing) and its requirements (e.g. having babel installed).

**Comment by gtramontina** [comment]
Yeah, my memory is failing on reminding me the reasons why we added babel (I'm on my phone, kinda painful to go through the git history to find out). My guess would be to support old node versions, as you mentioned. I'm all for it!

**Comment by gtramontina** [comment]
Closed by https://github.com/ghooks-org/ghooks/pull/218
