### ISSUE TITLE
Parameter not forwarded to commit-msg hook

### ISSUE THREAD

**Issue by 0815fox** [ghooks-org/ghooks#227]
I have the following commit-msg hook:

```
#!/bin/bash
echo $1

```
Which simply echos the file passed as argument to the script. When I install my hook directly the following is echoed:
`.git/COMMIT_EDITMSG`
When I run the script with ghooks, how can I get access to that argument?

```
"config": {
    "ghooks": {
      "pre-commit": ".githooks/pre-commit",
      "commit-msg": ".githooks/commit-msg"
    }
  },
```

Guessing from code I also tried the following:
```
"config": {
    "ghooks": {
      "pre-commit": ".githooks/pre-commit",
      "commit-msg": ".githooks/commit-msg $1"
    }
  },
```
but it did not work.

Apologizes in case I have overseen something obvious.

**Comment by ta2edchimp** [comment]
That should work similarly to what you guessed. But while the first argument passed will be the hooks' file, the one you are searching for will be the second argument.  
So

```
  "commit-msg": ".githooks/commit-msg $2"
```

should pass `.git/COMMIT_EDITMSG` to your bash script.

**Comment by 0815fox** [comment]
That's what I was missing, thank you. Would be a nice hint in readme IMO.
