### ISSUE TITLE
Specify project root manually

### ISSUE THREAD

**Issue by jukkasi** [ghooks-org/ghooks#28]
I need to be able to set project root manually.

The directory structure I have is 

git_root\frontend

where git_root contains .git and frontend contains package.json where I run npm

When I run <git_root>\frontend\npm install I get "This does not seem to be a git project"

**Comment by kilianc** [comment]
@jukkasi do you have frontend and backend as well I suppose, do they share the same hooks?

**Comment by jukkasi** [comment]
@kilianc yes I have backend as well but I only need hook on frontend

**Comment by kentcdodds** [comment]
Hi @jukkasi, sorry to be so late getting back to you. I'd like to make this work for you. We'll see if I (or someone else or you) finds time to do it :D Related to #3

**Comment by gtramontina** [comment]
As mentioned on https://github.com/gtramontina/ghooks/issues/35#issuecomment-169160799, I'm copying it here for clarity:

>  Btw, would allowing a config like root: "./my-dir" in the package.json help in any way?

My only concern is where would this fit under `config.ghooks`, as everything under `ghooks` are git hooks names currently. Simply adding a `root` there would be confusing. A couple of suggestions that come to my mind without thinking too hard:

1. Create `config.ghooks-root`.
2. Move all hooks to `config.ghooks.hooks` and create `config.ghooks.root`.

Option number 2 keeps everything under the same config "namespace", but it introduces a breaking change. Options number 1 would not require a major release, but it kinda breaks the `config > package_name` "pattern".

:thought_balloon:?

**Comment by kentcdodds** [comment]
How about we do this in phases:

1. Implement both with a deprecation warning. So you can either use `hooks` and `root` or you can use `ghooks` and `ghooks-root`. Either works, but the second will log a deprecation warning.
2. In a major version bump we remove the old way and the deprecation warning.

**Comment by gtramontina** [comment]
Sounds like a plan!

**Comment by fingermark** [comment]
How do I get this working?  I have project_root/path/to/frontend/{node_modules/,package.json}.  The plan is to run "npm run lint" as a pre-commit.  .git is in my project_root.

I keep getting:

```
ghooks not found!
Make sure you have it installed on your "node_modules".
```

In package.json I added

```
  "config": {
    "ghooks": {
      "root": "./path/to/frontend",
      "pre-commit": "npm run lint"
    }
  }
```

**Comment by kentcdodds** [comment]
This is yet to be implemented: https://github.com/gtramontina/ghooks/issues/81

**Comment by ta2edchimp** [comment]
Wouldn't #108 solve this?

**Comment by kentcdodds** [comment]
Looks like it

**Comment by hally9k** [comment]
I've been traversing the tree of issues relating to this but I can't seem to find a working work around. My `package.json` is nested a few directories deeper than my git root. On Windows I'm getting 'no such file or directory' as it's looking for my `package.json` in the git root. Is there an existing work around for this? Apologies if I've over looked it!

node: 4.4.5
npm: 3.9.6
ghooks: 1.3.2

**Comment by ta2edchimp** [comment]
>On Windows I'm getting 'no such file or directory'

Does this happen during the installation of ghooks or when running a git hook (via its corresponding command, eg. `git commit` when having set up a `pre-commit` hook)?

In general, having the package.json nested deep below the git root, should work.
Please note though, that the hooks' commands will be executed relative to the git root, not to where your package.json resides (see [here](https://github.com/gtramontina/ghooks/issues/78#issuecomment-230289144) for the corresponding discussion) — maybe this is something we could make configurable in a future release.

**Comment by hally9k** [comment]
Sorry I was in a meeting... This is observed when the` pre-commit` hook is triggered on calling `git commit`. I understand the issue now though. How can I make the following config run in the nested npm root then?

`  "config": {
    "ghooks": {
      "pre-commit": "npm run validate"
    }
  },`

**Comment by gtramontina** [comment]
Hey @hally9k, I believe that with the current behaviour you'd have to have something like:
`"pre-commit": "cd into/where/package_json/is; npm run validate"`

As @ta2edchimp mentioned, maybe this is something we could make configurable…

**Comment by gtramontina** [comment]
As a side node, I've just opened a PR documenting the current behaviour: https://github.com/gtramontina/ghooks/pull/126

**Comment by hally9k** [comment]
Cool, nice one @gtramontina !

This work around you proposed doesn't seem to work for me on this setup.
The following results in `The system cannot find the path specified.`
```
  "config": {
    "ghooks": {
      "pre-commit": "cd src/npm-root-directory; npm run validate;"
    }
  },
```
Evan a full path string from `C:\` throws the same error. I am probably doing something silly though... Hmmm...

**Comment by hally9k** [comment]
For some reason unknown to me the following works on my setup... Probably just Windowsy idiosyncrasies...

```
  "config": {
    "ghooks": {
      "pre-commit": "cd src/npm-root-directory && npm run validate;"
    }
  },
```

**Comment by jhabdas** [comment]
@hally9k have you migrated to husky? if so, and you are not experiencing this issue, please ping me so I can reopen this.
