### ISSUE TITLE
Add support for GUIs

### ISSUE THREAD

**Issue by kentcdodds** [ghooks-org/ghooks#40]
I think that we could potentially fix the issues with GUIs by making the githooks use the system's default shell scripting language (not sure what it is for Windows). Then it would set the PATH and call into the node stuff. Thoughts?

**Comment by gtramontina** [comment]
Do you mean something like this https://github.com/gtramontina/ghooks/issues/18#issuecomment-107376391?

**Comment by kentcdodds** [comment]
Yeah, I think so

**Comment by gtramontina** [comment]
The advantage of using node as the script language is that by having node installed, we shouldn't care which OS it is running on?

AFAIK Windows' command prompt does not interpret shebangs... A quick search gave me this: http://whitescreen.nicolaas.net/programming/windows-shebangs

**Comment by kentcdodds** [comment]
Right. I think I have a fundamental misunderstanding of the problem and a good solution. All I know is several of my coworkers use GUIs and I want them to be able to continue to do so without having to do any extra work.

**Comment by gtramontina** [comment]
I see. So maybe we could go with something like https://github.com/gtramontina/ghooks/issues/18#issuecomment-107376391 first and then figure Windows out, but this could potentially break existing windows users. I'll ask on gitter to see we there are any windows users who would help out. Meanwhile, a virtual box is being installed... :stuck_out_tongue:

**Comment by BarryThePenguin** [comment]
FWIW ghooks works fine on my machine SourceTree. I know there's a lot of other scenarios (especially on windows), happy to be a guinea pig!

**Comment by gtramontina** [comment]
@BarryThePenguin thanks for chiming in! :beers:
Do you happen to use window's default prompt for command line usage?

**Comment by BarryThePenguin** [comment]
Not regularly. I use MinGW (Git for Windows), which I also used to install *nix tools to my PATH

**Comment by BarryThePenguin** [comment]
Another update. SourceTree v1.8.2.0 on windows now no longer works. Same problem as in OSX now...

**Comment by kentcdodds** [comment]
So I just saw [this](https://github.com/sindresorhus/alfy) which apparently can [find the node binary](https://github.com/sindresorhus/alfy/blob/master/run-node.sh)!!! We could open source that script and use it here :D

**Comment by gtramontina** [comment]
Nice! I saw that @sindresorhus already has that in the works…

I guess that the shebang would also have to become a variable in the [raw template](https://github.com/gtramontina/ghooks/blob/c858ccd5b6ca7714a583d2c1e598eb4242ac19ee/lib/hook.template.raw#L1), then…

**Comment by sindresorhus** [comment]
Here you go: https://github.com/sindresorhus/run-node

**Comment by njpanderson** [comment]
Hi all - are you any closer to resolution on this issue, out of interest?

**Comment by kentcdodds** [comment]
I haven't worked on it any further, but I think with @sindresorhus's new module you could probably make it work if you wanted to [makeapullrequest.com](http://makeapullrequest.com) :)

**Comment by mmmpie** [comment]
In our git hook scripts we have to source an environment to get them to run in gui clients. Its a bit convoluted, given all the possibilities for environment setup.

**Comment by kentcdodds** [comment]
Could you try switching to [husky](https://github.com/typicode/husky) and letting us know how that goes? I proposed we deprecate ghooks in favor of husky #166

**Comment by thecotne** [comment]
@kentcdodds husky also have problems with GUIs https://github.com/typicode/husky/issues/87

**Comment by jhabdas** [comment]
@kentcdodds is this a bug or an enhancement request?

**Comment by kentcdodds** [comment]
I guess it's an enhancement because it never worked in GUIs...

**Comment by jhabdas** [comment]
Potentially related: https://github.com/observing/pre-commit/issues/56
